# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dash', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='avatard',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='avatar',
            field=models.FileField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='userim',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
